# Autogenerated wrapper script for QuEST_jll for aarch64-apple-darwin
export libquest

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("QuEST")
JLLWrappers.@declare_library_product(libquest, "@rpath/libQuEST.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libquest,
        "lib/libQuEST.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
