# Autogenerated wrapper script for QuEST_jll for x86_64-linux-gnu
export libquest

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("QuEST")
JLLWrappers.@declare_library_product(libquest, "libQuEST.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libquest,
        "lib/libQuEST.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
